### ISSUE TITLE
Login Functionality using Steemconnect

### ISSUE THREAD

**Issue by the-codingninja** [knacksteem/knacksteem.org#1]
Make a boilerplate which allows to login using steemconnect and gets user data from Steem(like user image).

**Comment by bannik** [comment]
this is initialized on commit ed519e2e70d5aa460942626ef16c1bdf6a59a483

I am guessing I will have to wait for the backend for this task to be finalised. Or should I store this token localy and that's it?

**Comment by AneilPatel05** [comment]
The front end needs to make another API call to sc2.me and get the user object.

**Comment by bannik** [comment]
@AneilPatel05 This works properly now. I will have to clean up the code now to add the correct actions to it and save the data properly.
