### ISSUE TITLE
Using the voting slider on mobile device causes the web page to lose fitted to display optimization. 

### ISSUE THREAD

**Issue by HarryHeights** [knacksteem/knacksteem.org#100]
#### Expected behavior
The UI  of Knacksteem's webpage when accessed on a mobile phone is fitted to display. I expected that that orientation would be consistent even when I try to use the voting slider. 

#### Actual behavior
When I want to upvote a post, the voting slider pops up but it changes the orientation of the display. The display is no longer fitted to display

#### How to reproduce
- Goto [Knacksteem](https://knacksteem.org) using your mobile phone
- Login 
- Open any post on the feed
- Try to like or upvote the post
- See error

* Device: Redmi Note 5 Pro
* Browser/App version: Google Chrome
* Operating system: Android 8.1

**Comment by onozasi** [comment]
Hello, @HarryHeights. Thank you for reporting this to us. You are experiencing this behaviour because the slider was not developed to be responsive on mobile. This is now fixed on PR #101.
