### ISSUE TITLE
Undefined data when opening profile from URL

### ISSUE THREAD

**Issue by jayserdny** [knacksteem/knacksteem.org#106]
Steps to reproduce:

1 - Navigate to any profile page using this URL https://knacksteem.org/@<username>, for example, https://knacksteem.org/@jaysermendez
2- See the name showing as undefined, reputation incorrect,  and the voting value is not correct.

![image](https://user-images.githubusercontent.com/19354816/52609379-f62e1080-2e31-11e9-8e63-3e72cd645912.png)

**Comment by codingdefined** [comment]
Not able to reproduce, it's showing the data in my local.

**Comment by onozasi** [comment]
This is tricky. Could not reproduce it at first but after multiple refreshes, I was able to reproduce. Navigating to a user's profile whose data is not registered on DB yet throws an undefined error in an instance looking like the screenshot Jayserdny had provided above.

**Comment by michygeek** [comment]
I was able to reproduce the issue and I could provide a Gif if highly needed.
