### ISSUE TITLE
Not needed votes call for each comment

### ISSUE THREAD

**Issue by jayserdny** [knacksteem/knacksteem.org#107]
I believe it is bad to let frontend handle all these requests to get the votes count of a comment. These numbers are already given in backend response. Want to add the list of voters of each comment as well? It can be implemented in the backend and just consume in the frontend.

This is causing too many 404 errors because for us, comments are not posts and thus the API will fail for comments. 

![image](https://user-images.githubusercontent.com/19354816/52609889-be27cd00-2e33-11e9-8628-65390c098b54.png)

In addition, on the home page, why calling the votes API is a voter modal is not being shown?

**Comment by codingdefined** [comment]
Yes, it would be good to have the list of voters for comments, so that we can show that information in the frontend. I will fix his 404 errors by not calling the endpoint if its a comment.

**Comment by onozasi** [comment]
Will include this on the list of TODO for the back-end. Not calling the endpoint would be cool. At least for now.
