### ISSUE TITLE
Automatic redirection to steemit when a user profile was searched and clicked on Knacksteem. 

### ISSUE THREAD

**Issue by HarryHeights** [knacksteem/knacksteem.org#114]
## Expected Behavior
I expected that since Knacksteem has its own user profile page, that I could visit a user's profile page on Knacksteem. 
## Actual Behavior 
I wanted to visit a user's profile, I searched for the user, click on the search result and the user's profile was opened on Steemit.

## How to reproduce
- Login to Knacksteem.
- Search for a user.
- Click on the search results.
- See error. 

## Video recording 

https://youtu.be/PfG7E8Vm-vg

**Comment by onozasi** [comment]
Thank you for reporting this. This behavior is not an error with the code, however, we will work on redirecting users to their knacksteem profile instead of steemit. The steemit link is only there as a place holder.

**Comment by onozasi** [comment]
Fixed now: https://github.com/knacksteem/knacksteem.org/blob/develop/src/containers/Search/index.js#L86
