### ISSUE TITLE
Search results are limited to only users who have login on Knacksteem at least once.

### ISSUE THREAD

**Issue by HarryHeights** [knacksteem/knacksteem.org#115]
I don't know if that's how the platform was designed to work. 
I tried searching for random steemians using the search bar, no results came. 
I tried searching for users I know that should have logged in at least once on Knacksteem and there was a result.

I'm not sure if that is an intended behavior, but if it is, it would have been great if other users could be searched through Knacksteem while post is limited to only Knacksteem.

**Comment by onozasi** [comment]
This behavior is normal. The search feature returns post/users data from our DB.
