### ISSUE TITLE
Images uploaded as links don't show when the post is opened. 

### ISSUE THREAD

**Issue by HarryHeights** [knacksteem/knacksteem.org#122]
Since images can't currently be uploaded on Knacksteem using the post editor, I opted to use hackmd post editor to create my content. 
In the content, I uploaded images to it as links. As expected, the image will be uploaded just by pasting the link in the post editor. 
I did that and then copied the content to Knacksteem's post editor but the image I uploaded using a link only showed as the link. 
I copied same content to steemit and it displayed properly. 

What makes this more weird is the fact that, the cover image of the post was uploaded as a link. But on the post preview, the image shows, but when I open the post it doesn't.

Here's a link to the video 

https://youtu.be/5t0LV1F5Wvs

The images showing in the video were actually uploaded on Hackmd and not as links. That's why they are visible.

**Comment by onozasi** [comment]
This has happened because you did not use the appropriate markdown to display your image. Pasting just the link won't work, it has to be in the following format `![](link to the image in here)`

**Comment by HarryHeights** [comment]
@onozasi I guess I made a mistake in the manner I explained the error. I know about uploading an image as a link using that method you specified. But what I was actually saying wasn't that type. 
Now on Steemit, when I search for an image on google or anywhere else, and I wish to use that image in my post, I simply copy the image URL and paste it on the post editor. The image uploads that way too. 
That's what I did

**Comment by onozasi** [comment]
Hi @HarryHeights, Knacksteem editor requires you to use the recommended markdown (as suggested above) to be able to handle or display your image correctly.

**Comment by HarryHeights** [comment]
Oh Okay! For convenience sake though, it could have also been done the way I explained above too. Just copying and pasting the link of the image address. 
But what do I know?

**Comment by onozasi** [comment]
Edit the post and add the image address or link in the following format -> `![](link to the image in here)`

**Comment by HarryHeights** [comment]
Okay. I will do that.
