### ISSUE TITLE
KNT count doesn't show on my profile page when accessed using my mobile phone

### ISSUE THREAD

**Issue by HarryHeights** [knacksteem/knacksteem.org#134]
#### Expected Behaviour

KNT  distribution is going on at the moment and the count is being displayed on my profile page when I access Knacksteem on my PC. I expected to see same information when I access the webpage using my mobile phone. 

#### Actual Behaviour 
I can't find the KNT  count on my profile page when I accessed the webpage using my mobile phone.

#### How to reproduce

- Login to Knacksteem using a mobile phone.
- Navigate to user profile
- See error

#### Test Environment 
Device: Redmi Note 5 Pro
OS: Android 8.1

#### Screenshot

![screenshot_2019-02-24-17-19-37-293_com android chrome](https://user-images.githubusercontent.com/40593824/53301925-c3840f00-3858-11e9-8a72-c5d124fa03ba.png)

**Comment by onozasi** [comment]
Hi, @HarryHeights. Thank you for reporting this. Actually, this is not an error, this behavior is expected, however, having the count show up for mobile users is something we are still working on by making the site completely responsive with all desktop features available for mobile users.

**Comment by HarryHeights** [comment]
Oh okay.
