### ISSUE TITLE
wallet and activity feature not wworking

### ISSUE THREAD

**Issue by muhammadarif1** [knacksteem/knacksteem.org#138]
expexted behavior
 when user clicking wallet and activity option user should can see transaction info on  that account.

actual behavior
 when user click on that option nothing displayed on that tab.

https://youtu.be/xpdEBEbT9ZA

**Comment by onozasi** [comment]
Hi, @muhammadarif1. This behavior is expected. The Notification sign, wallet, followers, following, and the activity tabs are simply a place holder for now.
