### ISSUE TITLE
[Copywriting] KnackSteem annoucement post

### ISSUE THREAD

**Issue by onozasi** [knacksteem/knacksteem.org#14]
Looking for a good copywriter to help proof-read our announcement blog
Hackmd doc: https://hackmd.io/JjOCLJClTfm4q_V66-gsJg

**Comment by wmetryka** [comment]
As we've talked about in DMs, I'm up for it. Not the best proofreader out there, but definitely have some skills up my sleeve! Check the proofread version I've submitted!

**Comment by onozasi** [comment]
Hi Thank you for helping out here, very well appreciated.
