### ISSUE TITLE
BUG; There's an anomaly when I open another author's profile page. 

### ISSUE THREAD

**Issue by HarryHeights** [knacksteem/knacksteem.org#147]
#### Expected behavior 

I expected that when I click on an author's name, his/her profile will open up.

#### Actual behavior

When I click the author's username, the profile page opens but it has constituents of my own profile too. 

- The username shown is mine
- The profile cover image is mine
- The profile information is mine

The rest of the content on the page except from those I listed above, are that of the author.

#### How to reproduce

After logging in to Knacksteem
-  Click on the username of any author you find on posts in the feed.
- See error

#### Test Enviroment

- Device: HP pavilion dv7
- OS: Windows 7 Professional
- Browser version: Google Chrome v70

#### Video of error

https://youtu.be/FXuwA4LMfFc

**Comment by onozasi** [comment]
Thanks for reporting this. However, this is a duplicate report: #106
