### ISSUE TITLE
Following, Wallet and Activity on User profile not clicking 

### ISSUE THREAD

**Issue by tony-duke** [knacksteem/knacksteem.org#149]
## Expected Behaviour
I expected that when I clicked on those options,  I will be directed to their different pages. 

### Actual Behavior 

No action was taken. It just highlighted. Only **followers** and **edit profile** options are clicking. 

Using latest version of Chrome browser with an Android 7.0

**Comment by onozasi** [comment]
Duplicate #138. These are features that is yet to be implemented.
