### ISSUE TITLE
Steemconnect log in not working

### ISSUE THREAD

**Issue by AneilPatel05** [knacksteem/knacksteem.org#17]
Upon Log In, the user should be redirected to steemconnect auth page, but an error is encountered with error  code 404.

looks like the steemconnect app dashboard needs http://knacksteem.org/callback into the app config.

**Comment by onozasi** [comment]
Hi! This has been fixed in PR https://github.com/knacksteem/knacksteem.org/pull/16. Thank you for reporting.
