### ISSUE TITLE
Proposal to help with Copywriting of this project.

### ISSUE THREAD

**Issue by HarryHeights** [knacksteem/knacksteem.org#19]
Hello, I'm Harry.

I know this project is still in it's development stages and hasn't been fully implemented however, it won't be to late to start getting the world especially on the steem blockchain ready for this revolution. 

As you may have already known, copywriting is a valuable asset in these modern day that creates good influence for a project. 

It'll be great honor to contribute to this project.

**Comment by onozasi** [comment]
Hi, Thank you for wanting to help improve this project. Please get in touch with *knowledges* on our [discord server](https://discord.gg/t5RhBvE)

**Comment by HarryHeights** [comment]
Alright. I'll do
