### ISSUE TITLE
[Copywriting] Creating a policy/guideline copy for Knacksteem

### ISSUE THREAD

**Issue by onozasi** [knacksteem/knacksteem.org#22]

**Comment by frankremmy** [comment]
Hi @onozasi. Warm greetings to you,

I may not be considered as the perfect match for the task at hand. But if the necessary materials for the content are provided, and there is a room to showcase my skills and abilities (according to the project itself), in due time, you will consider this task accomplished. 

Thanks in anticipation.

**Comment by onozasi** [comment]
Thanks. I will now close this issue since it has achieved its purpose.
