### ISSUE TITLE
Firefox - error while loading knacksteem.org

### ISSUE THREAD

**Issue by outwork** [knacksteem/knacksteem.org#24]
When i try to access knacksteem in firefox (latest version) the following error message appears: "error getting categories" and only the sidebar loads, without categories. When i hit login button, it gets redirected to https://v2.steemconnect.com/404

Everything works fine in chrome.
I use hungarian version of firefox, but it something has to do with CORS requests it says: CORS request was unsuccessfully.
![bug](https://user-images.githubusercontent.com/18143389/43740239-5c7bcfba-99d3-11e8-8c3a-f65c5988c4b0.PNG)

**Comment by the-codingninja** [comment]
Try https://www.knacksteem.org

**Comment by josephace135** [comment]
I experience also the same scenario both in Firefox version 61.0.1 and Chromium version 58.0.2988.0.

**Comment by the-codingninja** [comment]
@josephace135 @outwork As i said use https version of the app :slightly_smiling_face:
