### ISSUE TITLE
Users unable to login to knacksteem.org

### ISSUE THREAD

**Issue by jubreal** [knacksteem/knacksteem.org#30]
#### Expected behavior
Users should be able to login to the knacksteem platform to perform various steemit activities via steemconnect secured platform.

#### Actual behavior

Users login ID not successful sue to inability to get callback. 
 

#### How to reproduce
- Launch your chrome web browser.
- Enter "https://knacksteem.org" into the address bar and wait for it to load.
- Click on login button appearing on the front end
- Input your correct Steemit login details

It would be observed that the login attempt was not successful sue to callback error. 

* Browser/App version: Chrome version 68.0.3440.91
* Operating system: Android version 6.0

#### Recording Of The Bug

https://youtu.be/kxE9p__NfTY

**Comment by onozasi** [comment]
Hey @jubreal, I will be glad if you could provide more information about this behavior. The page works for me perfectly without any flaws.
