### ISSUE TITLE
The side menu bar is not working correctly

### ISSUE THREAD

**Issue by onozasi** [knacksteem/knacksteem.org#58]
Some tabs are hidden for "normal users" without an administrative role. The "reserved/pending" tab should display for users with the following role; Master sup, sup, and mod. The current version only displays those tabs for Master sup and mod but not for "sups." However, when sup is signed in and knows the correct permalink to access those hidden tabs, it works. 

It's a tiny fix.

**Comment by ogbiyoyosky** [comment]
Will work on this next

**Comment by onozasi** [comment]
Resolved.
