### ISSUE TITLE
''Moderator'' Not working and the side menu bar does not look aligned 

### ISSUE THREAD

**Issue by michygeek** [knacksteem/knacksteem.org#59]
All these issues occurred on Mozilla Firefox browser. 
![screenshot 1307](https://user-images.githubusercontent.com/35191441/49284128-802c2700-f448-11e8-8436-5af301def111.png)
The  ''Reserved'' tab is on top, but the ''Guidelines'' ''Faq'' and ''TOS'' are down below with another side bar. 

The ''moderator'' tab does not work or load at all.
![screenshot 1306](https://user-images.githubusercontent.com/35191441/49284502-a605fb80-f449-11e8-81ac-9d5d2647302a.png)

Let me know if you need more details to get this fixed. Thank you!

**Comment by ogbiyoyosky** [comment]
Fixed moderators tab

**Comment by onozasi** [comment]
Fixed and merged on PR #63
