### ISSUE TITLE
https:// redirect should be automatic

### ISSUE THREAD

**Issue by tobias-g1** [knacksteem/knacksteem.org#60]
#### Expected behavior

When a user attempts to launch Knacksteem via HTTP they should automatically be redirected to https:// 

#### Actual Behaviour

If you visit http://knacksteem.org it will not automatically redirect the user, it will instead cause cross-origin errors and the categories will not be loaded. 

#### Steps to reproduce

1. Go to http://knacksteem.org

#### Error Details

The following errors are present in the console upon load of http://knacksteem.org

![image.png](https://ipfs.busy.org/ipfs/QmR7PrrDE9K84PByryaDsnpY88ZfGWp1Js41coascwUaYM)

#### Issue resolution

This could potentially be resolved by using:

`express-force-https` in server.js

First define secure as below:

`const secure  =  require('express-force-https')`

and then add 

`app.use(secure)`

I can see that there is already `app.use(redirectToHTTPS([/localhost:(\d{4})/], [], 301));` within server.js and although I'm not familiar with that library, my solution may potentially conflict without me being able to conduct further testing. 

#### Environment

- Browser: Google Chrome (Version 65.0.3325.162 (Official Build) (64-bit))
- Device: MacBook Pro (Retina, 15-inch, Late 2013)
- Operating system: MacOS HighSierra Version 10.13

**Comment by the-codingninja** [comment]
Thanks @tobias-g1 I will surely try the package mentioned and check the results

**Comment by the-codingninja** [comment]
Thanks @tobias-g1 this issue is fixed now.

I have used the module you recommended and it works
