### ISSUE TITLE
Profile page shouldn't require refresh

### ISSUE THREAD

**Issue by tobias-g1** [knacksteem/knacksteem.org#61]
#### Expected Behaviour

The application should not need to reload when loading the profile page. 

#### Actual Behaviour

The application reloads when visiting the user profile page. 

#### Steps to Reproduce 

1. Go to https://knacksteem.org/
2. Sign in
3. Click on your user profile shown in the top right

#### About Issue

It looks like the profile option has not been correctly defined in your routes, currently it works as so:

```
<span className="ant-dropdown-link">
    <a title="Visit profile" href={`/@${user.username}`}>
         <Avatar size="small" src={`https://steemitimages.com/u/${user.username}/avatar`}  icon="user"/>
    </a>
 </span>
```

As you can see in the above the link for the profile page is defined using a standard HTML. This is causing the page to refresh when loading the profile page, with this type of behavior you will see the logout button appear briefly when loading the profile page. 

Although I'm not familar where you define the routes in React (maybe app.js), I would assume that the link for the router would be defined as something similar to the below:

```
<Link to="/profile">
<Avatar size="small" src={`https://steemitimages.com/u/${user.username}/avatar`}  icon="user"/></Link>
```

**Comment by ogbiyoyosky** [comment]
Thanks for reporting this issue. Its has now being resolved.
