### ISSUE TITLE
Unable to login to Knacksteem from landing page.

### ISSUE THREAD

**Issue by HarryHeights** [knacksteem/knacksteem.org#67]
#### Expected behavior
The landing page provides a portal to access the main website. The landing page has a login and sign up button to enable pre-exiting users login or non-existing users signup. I expected that I'd be able to login to Knacksteem using the login button on the landing page.

#### Actual behavior
After clicking the login button, the steemconnect security login protocol pops-up. After logging in, the Knacksteem page opens but, I'm not logged in. I have to login again using the button on the website.

#### How to reproduce
1. Access the landing page 
2. Click the login button
3. Login with steemconnect
4. Knacksteem webpage opens but user is not logged in.

* Browser/App version: Google Chrome v70.0.3538.102
* Operating system: Windows 7.

#### Recording Of The Bug
https://youtu.be/DtiTLqZVLLE

**Comment by onozasi** [comment]
Thanks for reporting this. It is now resolved.
