### ISSUE TITLE
 List out category on the editor page

### ISSUE THREAD

**Issue by onozasi** [knacksteem/knacksteem.org#80]
Should list the categories just as shown on this mockup below
![](https://steemitimages.com/640x0/https://cdn.steemitimages.com/DQmZocH1DPqX9n5anVCFGNjkAqd3GGrwTVbw1zpdbWxZ2Gx/Post%20editor.png)

Currently, a post made via the project front end is by default using #knacksteem as the first tag followed by the category-specific tag which must march one of the categories existing on the platform. This has to be done manually. But we could simplify it by allowing the user to only select the category they want to contribute into from the icons and the tag is automatically filled.

**Comment by nirvanaitsolutions** [comment]
I can implement this enhancement
