### ISSUE TITLE
fix image dimension on every post list

### ISSUE THREAD

**Issue by onozasi** [knacksteem/knacksteem.org#81]
![knacksteem rewarding talent 34](https://user-images.githubusercontent.com/31616620/51090488-01cbe000-177d-11e9-896b-ea8822df22ef.png)
There should be no empty space. All display image should have an equal dimension as shown below. 

![](https://steemitimages.com/640x0/https://cdn.steemitimages.com/DQmQk1C1EyypD7HrxN3AaUMmtL4k1RYwkcpo5Vf7Qj4hQwo/Home%20page.png)

**Comment by nirvanaitsolutions** [comment]
I can fix this bug

**Comment by onozasi** [comment]
The preview section seems not to be responsive. There is some redundant or irrelevant space displayed on the post preview. 

![knacksteem rewarding talent 42](https://user-images.githubusercontent.com/31616620/52995909-4271e580-341c-11e9-870a-a2900b86821f.png)
The above is the desktop view of the preview section, The image holder width could be stretched a bit to cover the redundant space.
