### ISSUE TITLE
Page should not reload when a user comments,  or edit a post

### ISSUE THREAD

**Issue by onozasi** [knacksteem/knacksteem.org#82]
Each time a user comments, or edits a post, the page does not update real-time. Instead, the page reloads. This could be problematic to users accessing the page with a poor internet connection. 
![page reload](https://user-images.githubusercontent.com/31616620/51101902-0922d600-17dd-11e9-80a5-4e9287d1125c.gif)

**Comment by nirvanaitsolutions** [comment]
I'll check and let you know if I can fix it
