### ISSUE TITLE
API request from the front-end for a single user is enormous. (Almost 3k requests in 2 mins) 

### ISSUE THREAD

**Issue by onozasi** [knacksteem/knacksteem.org#89]
The front-end needs to be better optimized to send a lesser request to the backend. Too many requests from multiple users on different tab could crash the API. This needs to be handled properly. 

![bad number of request sent to the api](https://user-images.githubusercontent.com/31616620/51850834-e509dd80-2322-11e9-85a8-90b8f27f9dc1.PNG)

**Comment by nirvanaitsolutions** [comment]
We can fix this.

**Comment by codingdefined** [comment]
@onozasi Is it still happening?

**Comment by onozasi** [comment]
Nop. Should be closed already.
