### ISSUE TITLE
The voting slider does not responsive/align on mobile

### ISSUE THREAD

**Issue by michygeek** [knacksteem/knacksteem.org#95]
Hello! 
The voting slider does not respond/align properly on mobile. I added two screenshot to show how it looks like.

![image](https://user-images.githubusercontent.com/35191441/51947941-7a68a880-23db-11e9-94a0-147767052853.png)

![image](https://user-images.githubusercontent.com/35191441/51947949-85233d80-23db-11e9-8e73-eb5eacfc5b9b.png)

**Test area screen size:**  5.45 inches (13.84 cm)

**Comment by onozasi** [comment]
Fixed with PR #101
