### ISSUE TITLE
Why are post/comment rewards information unavailable. 

### ISSUE THREAD

**Issue by HarryHeights** [knacksteem/knacksteem.org#98]
I don't think this is a bug but a missing feature. I scoured your to-do list and found out that this is not listed. So I assumed you might not entirely be aware of the situation. 
I'm suggesting that you implement the feature that will make post/comment rewards information available. 

It's quite weird that that information isn't available.  It is not available on post preview, it is not available when the post is opened.

**Comment by onozasi** [comment]
We do have this already implemented on the project but not routed yet to the UI. You can find the code responsible for articles reward information on this [page](https://github.com/knacksteem/knacksteem.org/blob/50a6a3b8ab76b26e3e0a202d65a73a51e0d1f276/src/actions/stats.js#L78). This will be made available very soon. PR is welcome.

**Comment by HarryHeights** [comment]
Oh okay. I'm not a dev. Would have fixed it.
